"""Add products JSON field to FeedbackCase

Revision ID: 0caf9e492337
Revises: 95c101c53b7b
Create Date: 2025-07-07 14:10:20.310662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0caf9e492337'
down_revision = '95c101c53b7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('products', sa.JSON(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_feedback_case_product_id'), type_='foreignkey')
        batch_op.drop_column('amount')
        batch_op.drop_column('product_id')
        batch_op.drop_column('quantity')
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_feedback_case_product_id'), 'product', ['product_id'], ['id'])
        batch_op.drop_column('products')

    # ### end Alembic commands ###
