"""Add extra fields to User Model

Revision ID: 2f56a1e3f8f1
Revises: eb060a187bc2
Create Date: 2025-06-23 21:40:53.407806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f56a1e3f8f1'
down_revision = 'eb060a187bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('num_trans_24h', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('num_failed_24h', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('no_of_cards_from_ip', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('no_of_cards_from_ip')
        batch_op.drop_column('num_failed_24h')
        batch_op.drop_column('num_trans_24h')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
