"""added probability in return request

Revision ID: 346bf5888305
Revises: 97f3fd828826
Create Date: 2025-07-07 23:00:59.002655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346bf5888305'
down_revision = '97f3fd828826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('probability', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_request', schema=None) as batch_op:
        batch_op.drop_column('probability')

    # ### end Alembic commands ###
