"""Add order_id to FeedbackCase

Revision ID: 3ef5f4fc8400
Revises: 32eee9ce39e5
Create Date: 2025-06-30 19:58:09.547423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef5f4fc8400'
down_revision = '32eee9ce39e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_feedback_case_order_id',  # <-- constraint name
            'order',                      # referenced table
            ['order_id'],                 # local column
            ['id']                        # remote column
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_case', schema=None) as batch_op:
        batch_op.drop_constraint('fk_feedback_case_order_id', type_='foreignkey')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
