"""Add detailed fields to ReturnRequest

Revision ID: 6118ed19b03a
Revises: 3e794833539c
Create Date: 2025-07-06 22:00:30.548355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6118ed19b03a'
down_revision = '3e794833539c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('device_type', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('delivery_status', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('return_requested', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('return_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('item_returned', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('item_condition', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('refund_issued', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('refund_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('chargeback_requested', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('chargeback_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('account_age_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('order_history_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('return_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('chargeback_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('transaction_amount', sa.Float(), nullable=True))
        batch_op.drop_column('fraud_flag')
        batch_op.drop_column('fraud_probability')
        batch_op.drop_column('reason')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('fraud_probability', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('fraud_flag', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('transaction_amount')
        batch_op.drop_column('chargeback_rate')
        batch_op.drop_column('return_rate')
        batch_op.drop_column('order_history_count')
        batch_op.drop_column('account_age_days')
        batch_op.drop_column('chargeback_reason')
        batch_op.drop_column('chargeback_requested')
        batch_op.drop_column('refund_amount')
        batch_op.drop_column('refund_issued')
        batch_op.drop_column('item_condition')
        batch_op.drop_column('item_returned')
        batch_op.drop_column('return_reason')
        batch_op.drop_column('return_requested')
        batch_op.drop_column('delivery_status')
        batch_op.drop_column('device_type')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
