"""Add product_id to FeedbackCase

Revision ID: 71f2c9249715
Revises: 3ef5f4fc8400
Create Date: 2025-07-01 00:42:41.437951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f2c9249715'
down_revision = '3ef5f4fc8400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_feedback_case_product_id',  # <-- constraint name
            'product',                      # referenced table
            ['product_id'],                 # local column
            ['id']                          # remote column
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_case', schema=None) as batch_op:
        batch_op.drop_constraint('fk_feedback_case_product_id', type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
