"""Add category and item_amount to OrderItem

Revision ID: 95c101c53b7b
Revises: 6118ed19b03a
Create Date: 2025-07-07 13:38:05.599264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c101c53b7b'
down_revision = '6118ed19b03a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('item_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('item_amount')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
