"""Add products JSON field to ReturnRequest

Revision ID: 97f3fd828826
Revises: 0caf9e492337
Create Date: 2025-07-07 14:16:02.541133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f3fd828826'
down_revision = '0caf9e492337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('products', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_request', schema=None) as batch_op:
        batch_op.drop_column('products')

    # ### end Alembic commands ###
