"""Add ForeignKey to FeedbackCase.product_id

Revision ID: b22ba1dd9b1c
Revises: 71f2c9249715
Create Date: 2025-07-01 00:46:40.885827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b22ba1dd9b1c'
down_revision = '71f2c9249715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_case', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_feedback_case_product_id', 'product', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_case', schema=None) as batch_op:
        batch_op.drop_constraint('fk_feedback_case_product_id', type_='foreignkey')

    # ### end Alembic commands ###
