"""empty message

Revision ID: dfcfab35041d
Revises: 2f56a1e3f8f1
Create Date: 2025-06-24 21:02:09.670567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfcfab35041d'
down_revision = '2f56a1e3f8f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.drop_column('no_of_cards_from_ip')
        batch_op.drop_column('transaction_hour')
        batch_op.drop_column('num_trans_24h')
        batch_op.drop_column('num_failed_24h')
        batch_op.drop_column('account_age_days')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('no_of_cards_from_ip')
        batch_op.drop_column('num_trans_24h')
        batch_op.drop_column('num_failed_24h')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_failed_24h', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('num_trans_24h', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('no_of_cards_from_ip', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_age_days', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('num_failed_24h', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('num_trans_24h', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('transaction_hour', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('no_of_cards_from_ip', sa.INTEGER(), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
