"""Add extra fields to Order model

Revision ID: eb060a187bc2
Revises: afaf34cfc50b
Create Date: 2025-06-23 21:33:26.919721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb060a187bc2'
down_revision = 'afaf34cfc50b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_age_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('device', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('num_trans_24h', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('num_failed_24h', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('no_of_cards_from_ip', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('transaction_hour', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('transaction_hour')
        batch_op.drop_column('no_of_cards_from_ip')
        batch_op.drop_column('num_failed_24h')
        batch_op.drop_column('num_trans_24h')
        batch_op.drop_column('device')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('account_age_days')

    # ### end Alembic commands ###
